substitutions:
  device_name: esp-185
  friendly_name: blueriiot
  description: "BlueRiiot Proxy"
  device_area: Piscine

  #blueriiot_mac: 00:A0:50:56:xx:xx
  #blueriiot_nameprefix: mySwimingPool
  #blueriiot_idprefix: p1

  blueriiot_mac: !secret blueriiot_mac
  blueriiot_name_prefix: !secret blueriiot_nameprefix
  blueriiot_id_prefix: !secret blueriiot_idprefix
  
  # send true 0x01 to this service ID
  blueriiot_send_service_uuid: 'F3300001-F0A2-9B06-0C59-1BC4763B5C00'
  blueriiot_send_characteristic_uuid: 'F3300002-F0A2-9B06-0C59-1BC4763B5C00'
  
  # notification is recieved on this Service ID                  
  blueriiot_recieve_service_uuid: 'F3300001-F0A2-9B06-0C59-1BC4763B5C00'
  blueriiot_recieve_characteristic_uuid: 'F3300003-F0A2-9B06-0C59-1BC4763B5C00'

#
esphome:
  name: ${device_name}
  area: ${device_area}

# Packages :
packages : 
  wifi: !include common/wifi-iot.yaml
  device_base: !include common/base.yaml
  esp32: !include common/esp32.yaml

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:
  #level: VERY_VERBOSE
  #level: VERBOSE
  level: INFO

# for BLE
wifi:
  power_save_mode: LIGHT 

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_esp-185

web_server:
  port: 80

esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 1000ms
    window: 700ms
  
ble_client:
  - mac_address: ${blueriiot_mac}
    id: ble_client_${blueriiot_id_prefix}
    on_connect: 
      then:
        - lambda: "id(binary_sensor_${blueriiot_id_prefix}_connected).publish_state(true);"
        - delay: 2s
        - button.press: button_${blueriiot_id_prefix}_doreading
    on_disconnect: [lambda: "id(binary_sensor_${blueriiot_id_prefix}_connected).publish_state(false);"]

## Blue Connect
button:
  - platform: template
    id: button_${blueriiot_id_prefix}_doreading
    name: ${blueriiot_name_prefix} do reading
    internal: true
    on_press:
      then:
        - ble_client.ble_write:
            id: ble_client_${blueriiot_id_prefix}
            service_uuid: ${blueriiot_send_service_uuid}
            characteristic_uuid: ${blueriiot_send_characteristic_uuid}
            # A lambda returning an std::vector<uint8_t>.
            value: !lambda |-
              return {0x01};
##
switch:
  - platform: ble_client
    ble_client_id: ble_client_${blueriiot_id_prefix}
    name: "${blueriiot_name_prefix} Enable"
    id: switch_${blueriiot_id_prefix}_enable
    restore_mode: ALWAYS_OFF
#              
binary_sensor:  
  - platform: template
    id: binary_sensor_${blueriiot_id_prefix}_connected
    name: ${blueriiot_name_prefix} Status
    device_class: connectivity
    entity_category: diagnostic

  - platform: template
    id: binary_sensor_${blueriiot_id_prefix}_ph
    name: ${blueriiot_name_prefix} pH Status
    # device_class: connectivity
    # entity_category: diagnostic
  
  - platform: template
    id: binary_sensor_${blueriiot_id_prefix}_orp
    name: ${blueriiot_name_prefix} Chlore Concentration
    # device_class: connectivity
    # entity_category: diagnostic
#
sensor: 
  - platform: template 
    id: sensor_${blueriiot_id_prefix}_temperature
    name: ${blueriiot_name_prefix} Temperature
    # Optional variables:
    unit_of_measurement: "°C"
    icon: mdi:thermometer-water
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
  
  - platform: template 
    id: sensor_${blueriiot_id_prefix}_ph
    name: ${blueriiot_name_prefix} pH
    unit_of_measurement: "pH"
    icon: mdi:ph
    state_class: "measurement"
    device_class: "PH"
    accuracy_decimals: 1
    on_value_range: 
      - below: 7.29
        then:
          - binary_sensor.template.publish:
              id: binary_sensor_${blueriiot_id_prefix}_ph
              state: OFF
      - above: 7.61
        then:
          - binary_sensor.template.publish:
              id: binary_sensor_${blueriiot_id_prefix}_ph
              state: OFF
      - above: 7.3
        below: 7.6
        then:
          - binary_sensor.template.publish:
              id: binary_sensor_${blueriiot_id_prefix}_ph
              state: ON
  - platform: template 
    id: sensor_${blueriiot_id_prefix}_orp
    name: ${blueriiot_name_prefix} Chlore
    unit_of_measurement: "mV"
    #icon: "mdi:water-percent"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 1
    on_value_range:
      - below: 649
        then:
          - binary_sensor.template.publish:
              id: binary_sensor_${blueriiot_id_prefix}_orp
              state: OFF
      - above: 751
        then:
          - binary_sensor.template.publish:
              id: binary_sensor_${blueriiot_id_prefix}_orp
              state: OFF
      - above: 650
        below: 750
        then:
          - binary_sensor.template.publish:
              id: binary_sensor_${blueriiot_id_prefix}_orp
              state: ON
  - platform: template 
    id: sensor_${blueriiot_id_prefix}_bat
    name: ${blueriiot_name_prefix} Batterie
    # Optional variables:
    #unit_of_measurement: "%"
    icon: mdi:battery-bluetooth-variant
    device_class: "BATTERY"
    state_class: "measurement"
    accuracy_decimals: 1
    
  - platform: template 
    id: sensor_${blueriiot_id_prefix}_salt
    name: ${blueriiot_name_prefix} Salinité
    # Optional variables:
    unit_of_measurement: "g/L"
    icon: mdi:shaker-outline
    state_class: "measurement"
    accuracy_decimals: 1
    
  - platform: template 
    id: sensor_${blueriiot_id_prefix}_cond
    name: ${blueriiot_name_prefix} Conductivité
    # Optional variables:
    unit_of_measurement: "µS/cm"
    #icon: "mdi:water-percent"
    state_class: "measurement"
    accuracy_decimals: 1
    

text_sensor:
  - platform: template
    name: Blueriiot last update
    id: uptime_blueriiot
    update_interval: never
    icon: mdi:clock-start
  - platform: ble_client
    id: ${blueriiot_id_prefix}_reading_data
    name: ${blueriiot_name_prefix} reading data
    internal: true
    ble_client_id: ble_client_${blueriiot_id_prefix}
    service_uuid: ${blueriiot_recieve_service_uuid}
    characteristic_uuid: ${blueriiot_recieve_characteristic_uuid}
    notify: true
    update_interval: never
    on_notify:
      then:
        - lambda: |-
            std::string rawhex = format_hex_pretty((uint8_t *) x.c_str(), x.size()).c_str();
            ESP_LOGD("raw_hex", "%s", rawhex.c_str());

            float temperature = (float)((int16_t)(x[2]<< 8) + x[1])/100;
            ESP_LOGD("temp", "%f", temperature);
            id(sensor_${blueriiot_id_prefix}_temperature).publish_state(temperature);
                
            float raw_ph = (float)( (int16_t) (x[4]<< 8) + x[3]) ;
            float ph = (float)( (int16_t) (2048 - raw_ph)) / 232  + 7 ; 
            ESP_LOGD("ph", "%f", ph);
            id(sensor_${blueriiot_id_prefix}_ph).publish_state(ph);
            
            float orp = (float)( (int16_t) (x[6]<< 8) + x[5]) / 3.86  - 21.57826;
            ESP_LOGD("orp", "%f", orp);
            id(sensor_${blueriiot_id_prefix}_orp).publish_state(orp);
            
            float salt = (float)( (int16_t) (x[8]<< 8) + x[7]) / 25.0;
            ESP_LOGD("salt", "%f", salt);
            id(sensor_${blueriiot_id_prefix}_salt).publish_state(salt);
            
            float cond = (float)( (int16_t) (x[10]<< 8) + x[9]) / 0.4134;
            ESP_LOGD("cond", "%f", cond);
            id(sensor_${blueriiot_id_prefix}_cond).publish_state(cond);
            
            float bat = (float)( (int16_t) x[11]);
            ESP_LOGD("bat", "%f", bat);
            id(sensor_${blueriiot_id_prefix}_bat).publish_state(bat);
            
            id(switch_${blueriiot_id_prefix}_enable).turn_off();
